### ISSUE TITLE
Does not work with Node v8

### ISSUE THREAD

**Issue by kylepeeler** [JedWatson/generator-react-component#15]
Broken dependency on require-dir within gulp-git, stack trace:

ypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/Kyle/Development/PactSafe/pactsafe-react-sdk/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/Users/Kyle/Development/PactSafe/pactsafe-react-sdk/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Kyle/Development/PactSafe/pactsafe-react-sdk/node_modules/react-component-gulp-tasks/tasks/release.js:1:73)

**Comment by florinn** [comment]
It seems there's an issue with `node 8` and the `require-dir` module.
 
As a workaround you may to install the latest version of `require-dir` (0.3.2).

**Comment by DMDc0de** [comment]
Got it working by `npm i require-dir@0.3.2` inside the `node_modules/gulp-git` folder
